name: Version, build, publish

on:
  push:
    branches:
      - main

jobs:

  semantic_release_publish:
    name: Publish to GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Run and publish
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
      - run: npm install
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
